# Generated by Django 3.1.4 on 2020-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201216_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_text',
            field=models.TextField(verbose_name='Описание бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_title',
            field=models.CharField(max_length=200, verbose_name='Номер бронирования'),
        ),
    ]
